### ISSUE TITLE
Missing Event : add_to_cart in container

### ISSUE THREAD

**Issue by Djo44200** [TagCommander/vue-tag-commander#15]
Hello,
I want to set up a click event.
I have an error message:
"Uncaught (in promise) Error: Missing Event: add_to_cart in container
    at TC_Wrapper.captureEvent (index.js? d7d0: 287)
    at VueComponent.onValidate (CompareChoiceData.vue? 4716: 168)
    at! click (eval at ./node_modules/cache-loader/dist/cjs.js? Icône"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"09ad2095-vue-loader-template "} ! ./ node_modules/@vue/cli-service/node_modules/vue-loader/lib/loaders/templateLoader.js?! ./ node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli -service / node_modules / vue-loader / lib / index.js?! ./ src / containers / ComparisonChoixDonnees.vue? vue & type = template & id = 320e1955 & scoped = true & (app.js: 2486), <anonymous>: 55: 42)
    at invokeWithErrorHandling (vue.runtime.esm.js? 2b0e: 1854)
    at HTMLButtonElement.invoker (vue.runtime.esm.js? 2b0e: 2179)
    at HTMLButtonElement.original._wrapper (vue.runtime.esm.js? 2b0e: 6917) ".

Here is the code:

<b-button
class = "ba-validateButton-btn"
: disabled = "disabledButton"
@ click = "onValidate ($ event)"
>
-----------------------------------
const remove_from_cart = {
PRODUCT_NAME: this.siteId,
};
const wrapper = TC_Wrapper.getInstance ();

wrapper.captureEvent ('add_to_cart', event, remove_from_cart);
-----------------------------
Can you help me?

**Comment by RomainLK** [comment]
Hello,

Considering the error message, it seems like there is an issue with your container configuration. For these kind of issue, yourshould contact Commanders's act support service so that they can help you with your configuration:

support@commandersact.com

You will need to provide your site id, the container in which the event "add_to_card" should be available, the list of container loaded on your site, and anything you think will be useful to determine why the event can't be found by this plugin. You can also link this ticket in your support request.
